// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config"; // Added the missing '@' symbol here

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Tell the CLI to use your direct connection for db push and migrations
    url: process.env["DIRECT_URL"], 
  },
});